# Generated by Django 3.2.4 on 2021-06-10 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Colaborador', '0001_initial'),
        ('Unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=250)),
                ('ramal', models.IntegerField()),
                ('bloco', models.CharField(max_length=2)),
                ('horario_funcionamento_inicio_turno1', models.TimeField()),
                ('horario_funcionamento_final_tuno1', models.TimeField()),
                ('parada', models.BooleanField()),
                ('horario_funcionamento_inicio_turno2', models.TimeField()),
                ('horario_funcionamento_final_tuno2', models.TimeField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colaborador.colaborador')),
                ('unidade', models.ManyToManyField(to='Unidade.Unidade')),
            ],
        ),
    ]
